Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -7,8 +7,7 @@ permissions:
 on:
   workflow_dispatch:
   push:
-    branches:
-      - main
+    branches: [main]
     paths:
       - 'API/src/StellarPath.API/db/migrations/**'
 
@@ -22,51 +21,40 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Configure AWS credentials using OIDC
+      - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4.0.1
         with:
           role-to-assume: arn:aws:iam::574836245203:role/GitHubActionsOIDCRole
           role-session-name: GitHub_to_AWS_via_FederatedOIDC
           aws-region: af-south-1
-      
-      - name: Verify AWS credentials
+
+      - name: Verify AWS access
         run: |
-                aws sts get-caller-identity
-                aws s3 ls s3://stellar-path-s3-bucket/ || echo "Cannot list bucket contents"
-                  
-      - name: Setup Terraform
+          aws sts get-caller-identity
+          aws s3 ls s3://stellar-path-s3-bucket/ || echo "Cannot list bucket contents"
+
+      - name: Setup and initialize Terraform
         uses: hashicorp/setup-terraform@v2
 
-      - name: Terraform Init
+      - name: Terraform Init and Output
         run: |
-              cd terraform
-              terraform init
-        env:
-          AWS_REGION: af-south-1
+          cd terraform
+          terraform init
+          terraform output
 
-      - name: Debug Terraform Outputs
-        run: |
-              cd terraform
-              terraform output
-
-      - name: Get Terraform Outputs
+      - name: Extract Terraform Outputs
         uses: dflook/terraform-output@v1
         id: tf-outputs
         with:
           path: terraform
 
-      - name: Print Terraform Outputs
+      - name: Print Terraform Outputs (Debug)
         run: |
           echo "RDS Endpoint: ${{ steps.tf-outputs.outputs.rds_endpoint }}"
-          echo "ecr_repository_url: ${{ steps.tf-outputs.outputs.ecr_repository_url }}"
-          echo "ecs_cluster_name: ${{ steps.tf-outputs.outputs.ecs_cluster_name }}"
-          echo "ecs_service_name: ${{ steps.tf-outputs.outputs.ecs_service_name }}"
-          
+
       - name: Install PostgreSQL Client
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y postgresql-client
-          
+        run: sudo apt-get update && sudo apt-get install -y postgresql-client
+
       - name: Run Flyway validate and migrate
         uses: joshuaavalon/flyway-action@v3.0.0
         with:
